### ISSUE TITLE
Inleiding

### ISSUE THREAD

**Issue by StephanStanisic** [StephanStanisic/PWS#1]
Een goede inleiding heeft een hele duidelijke structuur en voor bijna elk verslag
is de structuur van een inleiding het zelfde. Toch is het schrijven van een
inleiding misschien wel het moeilijkste van het hele verslag. Een standaard
inleiding heeft de volgende onderdelen:
- Een introductie van het onderwerp: Wat is er interessant aan, hoe groot is
het probleem en waarom is het maatschappelijk relevant?
- De probleemstelling: Een goede probleemstelling kan worden afgeleid uit
de introductie. Je noemt de onderzoeksvraag en licht die toe. Vervolgens
noem de deelvragen en ook die licht je toe in enkele zinnen. Zie voor
meer informatie over het maken van een goede vraagstelling hoofdstuk 3:
De probleemstelling.
- De hypothese: In de hypothese probeer je je verwachtingen ten aanzien
van de onderzoeksvraag te formuleren. Die hypothese verwoord je in één
zin (bijv. Mensen in grotere steden hebben een slechtere gezondheid dan
bewoners van kleine steden). Je moet je hypothese natuurlijk wel kort
toelichten. Voor natuurprofielen geldt dat deze toelichting bestaat uit een
voorspelling van de resultaten “Als de hypothese juist is dan kan ik de
volgende resultaten verwachten uit mijn experiment omdat
…….(theoretische achtergrond)”. Deze voorspelling is gebaseerd op
literatuur die je gelezen hebt over het onderwerp. Immers, om de
hypothese/voorspelling te formuleren gebruik je de kennis die je over het
onderwerp hebt. Door de voorspelling te formuleren weet je direct of je
hypothese toetsbaar is (kan je het onderzoeken?) en heb je een idee over
de opzet van het experiment.
- Gebruikte onderzoeksmethoden: Je maakt waarschijnlijk gebruik van
verschillende soorten bronnen zoals: Literatuur, een enquête of een
interview. Beargumenteer je keuzes voor de verschillende bronnen en leg
uit voor welke deelvragen je deze bronnen gaat gebruiken.
- Indeling verslag: Leg tenslotte uit wat de structuur van jullie verslag is.
Welke hoofdstukken gaat de lezer tegen komen en wat valt daar in het
kort in te lezen?

**Comment by StephanStanisic** [comment]
# Rubric
- De relevantie en motivatie (evt. in voorwoord) van het
onderzoek wordt uitgebreid duidelijk gemaakt.
- Vraagstelling is netjes en helder geformuleerd.
- De hypothese en verwachtingen zijn overtuigend
geformuleerd.

**Comment by kjeldvdl** [comment]
Ons onderwerp gaat over informatiesystemen bij scholen en bedrijven. Dit is relevant omdat we veel informatie hebben die gedeeld moet worden. Er zijn nu erg veel informatiesystemen maar zijn ze allemaal goed en wat kan er verbeterd worden. Hier gaan we achter komen door middel van een beoordelingsmodel. We maken dit model op basis van literatuurstudie. Ook gaan we bij scholen langs om te kijken hoe de informatiesystemen daar zijn en hoe de leerlingen en de docenten er van vinden. Hiervoor maken we een enquête.

Onze hoofdvraag is: Hoe ontwikkel je een model om de kwaliteit van een informatiesysteem binnen het onderwijs en het bedrijfsleven te kunnen beoordelen. Om op onze hoofdvraag antwoord te krijgen hebben we een paar deelvragen. We krijgen antwoord op de deelvragen door de enquête, de beoordelingsmodel en literatuurstudie. We hebben gekozen voor een enquête omdat we graag ook naar de mening van de dagelijkse gebruikers van de informatiesystemen willen kijken. Ook maken we een beoordelingsmodel zodat we de informatiesystemen kunnen beoordelen op hoe goed ze zijn. We gebruiken de literatuurstudie om antwoord te krijgen op de deelvragen en om een beoordelingsmodel te maken.

In het verslag gaan we het hebben over wat informatiesystemen zijn, hoe het gesteld is met de toegankelijkheid van de leerling en de docenten binnen de informatiestromen binnen het onderwijs en waar een beoordelingsmodel aan moet voldoen om informatiesystemen te kunnen beoordelen
