### ISSUE TITLE
Onderzoeksvoorbereiding 

### ISSUE THREAD

**Issue by StephanStanisic** [StephanStanisic/PWS#3]
Sommige van de door jullie opgestelde vragen zul je misschien kunnen
beantwoorden met informatie die te vinden is in boeken of op het internet.
Echter voor je profielwerkstuk zullen jullie ook zelf nieuwe informatie moeten
creëren door middel van het afnemen van een interview, het uitzetten van een
vragenlijst of het doen van een experiment(natuurprofielen). We noemen dit ook
wel data verzamelen. Als je kiest voor een vragenlijst heb je het voordeel dat je
op basis van je data beter conclusies voor grote groepen mensen kan trekken,
terwijl je bij een interview veel gedetailleerdere data kan krijgen. Tenslotte
gebruik je voor vakken uit het natuurprofiel vaak een experiment om iets te
toetsen. Met de data die je verzamelt hoop je een goed antwoord te vinden op de
onderzoeksvraag. Dat gaat alleen niet vanzelf.

Een goede beschrijving en een juiste uitvoeren van je dataverzameling
(experiment) zorgt ervoor dat de informatie die je hebt verzameld, een hogere
validiteit heeft en ook betrouwbaarder is. De beschrijving is gedetailleerd,
stapsgewijs en “to the point”. Eén van de kenmerken van goed wetenschappelijk
onderzoek is dat het onderzoek herhaald moet kunnen worden door een andere
onderzoeker. Het onderzoek is dan betrouwbaar, als een andere onderzoeker
hetzelfde onderzoek uitvoert en er ongeveer dezelfde resultaten uit komen. Een
juiste beschrijving van de dataverzameling is dus erg belangrijk. Daarnaast moet
de werkwijze passen bij de onderzoeksvraag. Meet je met de vragenlijst, het
interview of het experiment wat je wilt meten? Als deze vraag met ‘ja’
beantwoord kan worden is je onderzoek valide (je meet wat je wilt meten).

## Vragenlijsten maken (maatschappijprofielen)
De eerste vraag die je moet zien te beantwoorden is wie je de vragenlijst wil
laten invullen. Als je iets wil zeggen over alle Nederlanders, moet je er
natuurlijk voor zorgen dat jouw respondenten (mensen die de vragenlijst
invullen) een afspiegeling zijn van de Nederlandse populatie. Als je alleen
leerlingen van het RSG interviewt houd je er geen rekening mee dat zij er
misschien hele andere opvattingen op na houden dan de rest van Nederland.
Voor deze opdracht is het daarom het slimst je te richten op jongeren in de
leeftijd van 12 t/m 18, dan heb je de respondenten voor het uitkiezen!
Verder moet je zorgen dat je genoeg mensen een vragenlijst laat
invullen. Als jij leerlingen uit de mavo, havo en het vwo wil vergelijken, moet je
ervoor zorgen dat je gemiddeldes gebaseerd zijn op genoeg mensen. Hoe lager
het aantal, hoe lager de betrouwbaarheid, want het kan maar net zo zijn dat een
bepaalde klas gemiddeld heel anders denkt over een bepaald onderwerp dan een
andere klas. Een goede richtlijn is om in ieder geval 75 ingevulde vragenlijsten te
hebben.

Tenslotte maakt het uit hoe je de vragen stelt. Zijn de vragen helder en
duidelijk? Zijn de antwoordcategorieën zo geformuleerd dat iedereen de
categorieën op de zelfde manier begrijpt? Zijn je vragen niet suggestief? We gaan
hier in de les nog meer aandacht aan besteden.

## Interviewen (maatschappijprofielen)
Bij een interview moet je vooral bedenken wie je wil interviewen. Als je
onderzoek gaat over geweld tegen publieke dienstverleners, is het interessant
om te spreken met een zo’n dienstverlener en als je onderzoek doet naar het
effect van zittenblijven op de motivatie van leerlingen kun je bijvoorbeeld
spreken met een coördinator of met leerlingen die zelf zijn blijven zitten.
Het voordeel van interviewen ten opzichte van een vragenlijst afnemen is
dat je veel meer de diepgang kan zoeken in het gesprek. Jij bent er in
tegenstelling tot het afnemen van een vragenlijst immers zelf de hele tijd bij en
kan na elke vraag besluiten of je nog meer wilt weten over dat onderwerp of dat
je door gaat naar de volgende vraag. Wel kost het afnemen van een interview
veel tijd en moet je natuurlijk een afspraak maken. Bedenk daarom op een tijdig
moment wie je wil interviewen, want volwassenen hebben het vaak druk en
het maken van afspraken kost ook tijd! Verder is het belangrijk dat je je
interview goed voorbereidt en dat je weet wat je wil vragen en hoe je vragen
stelt. Hoe beter je voorbereid bent, hoe makkelijker het gesprek en des te beter
de antwoorden!

## Experimentele opzet (natuurprofielen)
Een experiment is een zorgvuldig opgezette proef die jouw in staat stelt je
hypothese te toetsen. De kracht van een experiment is dat je alles wat van
invloed kan zijn op jouw onderwerp of ook wel afhankelijke variabele kunt
controleren. Je wil er voor zorgen dat je precies kunt meten wat het effect van
jouw onafhankelijke variabele is op je afhankelijke variabele. De opzet van je
experiment bespreek je in je werkwijze.

De werkwijze beschrijft de daadwerkelijke uitvoering van het
experiment. Hierin moet, naast een lijst van benodigde materialen, een aantal
zaken duidelijk beschreven zijn. Ten eerste de te observeren kenmerken: waar
wordt naar gekeken tijdens het onderzoek? Daarna worden de variabelen
genoemd die bij het onderzoek betrokken zijn: de afhankelijke en onafhankelijke
variabelen, en welke variabelen constant gehouden worden of random variëren.
Bijvoorbeeld: De invloed van kunstmest op de groei van planten kan onderzocht
worden door een bepaald aantal zaden met verschillende hoeveelheden van de
mest op te kweken. De hoeveelheid mest is de onafhankelijke variabele, de
afhankelijke variabele kan zijn de lengte, het gewicht, de zaadproductie of het
eiwitgehalte van de proefplanten na een bepaalde tijd. De variabelen die
constant gehouden worden of random kunnen variëren zijn bijvoorbeeld:
koolstofdioxide, temperatuur, lichtintensiteit.

Indien nodig en mogelijk wordt een blanco of controleproef in de opzet
meegenomen. Een blanco is niet altijd hetzelfde als de waarde &#39;nul&#39; van de
onafhankelijke variabele. Als er bijvoorbeeld met bacteriën op voedingsbodems
gewerkt wordt om te kijken of de groeisnelheid (afhankelijke variabele)
afhankelijk is van de hoeveelheid glucose (onafhankelijke variabele), worden er
uiteraard ook bacteriën op een voedingsbodem zonder glucose uitgeplaatst (dit
is de controleproef). Maar dat is niet de blanco. De blanco is dan een
voedingsbodem zonder bacteriën, om te kijken of er geen sprake is van
vervuiling van het kweekmedium of andere onverwachte effecten.
Een ander aspect van de proefopzet is dat er gekozen moet worden voor
een waarnemings- of meetinstrument (blote oog, loep of microscoop, welke
thermometer gebruik je?) met voldoende nauwkeurigheid en met een juist
bereik. Je kan bijvoorbeeld de geluidsterkte van het geluid dat een
straaljagermotor op 40 meter afstand produceert niet meten met een
decibelmeter met een bereik van 20-60 decibel. Ook moeten de juiste intervallen
gekozen worden(welke hoeveelheden glucose voeg je toe aan de
voedingsbodems?). Daarnaast wordt aangegeven op welke wijze de resultaten
gepresenteerd (grafieken en tabellen) worden en wordt aangegeven hoe vaak
metingen of waarnemingen herhaald worden. Om de resultaten veel
bewijskracht te geven/je onderzoek valide en betrouwbaar te maken zijn
voldoende metingen en herhalingen nodig!

## Een juiste werkwijze:

- Bevat een lijst met benodigdheden
- Is stap voor stap beschreven (als een kookboekrecept)
- Bevat een beschrijving van de afhankelijke en de onafhankelijke
variabele(n).
- Geeft alle andere mogelijk beïnvloedende variabelen weer en geeft
aan dat de onderzoeker deze zo mogelijk constant houdt tijdens het
onderzoek.
- Beschrijft het bereik en de intervallen van de gekozen waarden van
de onafhankelijke variabele, deze moeten passen bij de verwachte
variatie van de afhankelijke variabele.
- Beschrijft de gevoeligheid van het meetinstrument, deze moet passen
bij de te verrichten meting(en).
- Bevat een controleproef of blanco (om de invloed van een variabele
te beoordelen)
- Beschrijft het aantal metingen (herhalingen)

**Comment by StephanStanisic** [comment]
# Rubric
- In de inleiding of in een apart hoofdstuk
(onderzoeksopzet) is helder en gedetailleerd uitgelegd
hoe het onderzoek verricht gaat worden.
- De gekozen methode (experiment, enquête,
schaalmodel, interview, observatie) sluit aan bij de
onderzoeksvraag.
- De nodige voorbereidingen zijn goed en zorgvuldig
verricht (Enquêtes op niveau, opzet in detail
uitgewerkt, afspraken gemaakt etc)

**Comment by kjeldvdl** [comment]
Wij gaan een meetlat maken om te kijken of verschillende informatiesystemen van deze tijd voldoen aan de eisen van nu.
