### ISSUE TITLE
Onderzoeksvraag en deelvragen formuleren

### ISSUE THREAD

**Issue by StephanStanisic** [StephanStanisic/PWS#4]
Als je ervan overtuigd bent dat je onderwerp aan de criteria van deze opdracht
voldoet en er genoeg informatie te vinden is, kun je de definitieve
onderzoeksvraag vaststellen. Deze onderzoeksvraag vormt jouw centrale
leidraad door het onderzoek heen. Het doel van je onderzoek is een zo goed en
volledig mogelijk antwoord te geven op deze vraag.

Een goede onderzoeksvraag moet voldoen aan de volgende eisen:
- Niet te globaal: hoe algemener de vraag, hoe meer tijd je nodig hebt om
tot een antwoord te komen. Ook geldt: hoe algemener, hoe algemener je
antwoord wordt, je moet juist met een precies antwoord op een precieze
vraag komen! Daarom moet je vraag ook...
- Duidelijk afgebakend zijn. Je onderwerp en onderzoeksgebied zijn
duidelijk/concreet. Niet te breed.
- Eenduidig: de onderzoeksvraag kan je maar op 1 manier uitleggen.
- Haalbaar: de vraag moet te onderzoeken zijn met jouw beschikbare tijd
en middelen.
- Liever geen ja/nee-vraag: De vraag moet open gesteld worden en kan
dus bijvoorbeeld beginnen met: In hoeverre/Wat is de invloed van/In
welke mate.

## Tip:
Een goede onderzoeksvraag heeft vaak een van de volgende vormen:
- “Wat is de invloed van X op Y?”
- “In hoeverre wordt X verklaard door de toename van Y in de laatste
jaren.”
- “In welke mate heeft X geholpen Y te verminderen.”

Een goede onderzoeksvraag is niet eenvoudig te beantwoorden. Om tot een goed
onderbouwd antwoord te komen heb je deelvragen nodig. Deelvragen voldoen
in principe ook aan bovenstaande eisen, maar zijn wat simpeler van aard. Elk
antwoord op een deelvraag draagt zijn steentje bij aan het beantwoorden van de
onderzoeksvraag. Echter het is wel belangrijk dat je nadenkt over de vraag of de
deelvragen wel echt relevant zijn voor je onderzoeksvraag. Als jij voor biologie
een praktische opdracht maakt over watervervuiling zijn deelvragen over
vissterfte en bacteriën wellicht relevanter dan de vraag wat Greenpeace precies
onderneemt om vervuiling tegen te gaan. De deelvragen ondersteunen dus de
onderzoeksvraag.

Het is verder handig om je deelvragen in een logische volgorde te zetten zodat ze
een lopend verhaal opleveren. Wat voor jullie logisch is ligt vooral aan de
complexiteit/moeilijkheid van je vragen. Je begint je verhaal vaak met het
beantwoorden van minder complexe vragen. Tenslotte moet het aantal
deelvragen niet te groot zijn: beperk je tot een stuk of vijf, zes. Heb je meer of
minder nodig? Overleg dit dan met je begeleider!

**Comment by kjeldvdl** [comment]
Hoofdvraag:
Wat zijn de eisen voor goed werkende informatiesystemen bij verschillende organisaties.

Deelvragen:
Hoe kan een informatiesysteem beoordeeld worden.
Wat voor verschillende informatiesystemen zijn er en wat zijn de implementaties hiervan.
Hoe kan gemeten worden of een informatiesysteem correct geimplementeerd wordt.
Hoe kan gebruikersvriendelijkheid gemeten worden.

**Comment by JarnoMartens** [comment]
**Hoofdvraag**
Hoe ontwikkel je een model om de kwaliteit van een informatiesysteem binnen het onderwijs en het bedrijfsleven te kunnen beoordelen.

**Mogelijke deelvragen**
Hoe is het gesteld met de toegankelijkheid van de leerling gerelateerde informatiestromen binnen het onderwijs?

Aan welke eisen moet een beoordelingsmodel voldoen om de leerling gerelateerde informatiestromen binnen het onderwijs te meten?

**Comment by StephanStanisic** [comment]
Hoe is het gesteld met de toegankelijkheid van de verschillende informatiestromen binnen het onderwijs en het bedrijfsleven?

Hoe ontwikkel je een model om de kwaliteit van een informatiesysteem binnen het onderwijs en bedrijfsleven te kunnen beoordelen?
Hoe maak je een enquête die de mening van de gebruikers binnen een gegeven informatiestroom peilt?
